states:
- 0
- 1
- 2
- 3
initial: 0
accepting:
- 0
- 1
- 2
1:
  2: p_0 & ~p_1
  3: p_1 | ~p_0
0:
  1: p_1 & ~p_0
  2: p_0 & ~p_1
  3: (p_0 & p_1) | (~p_0 & ~p_1)
2:
  1: p_1 & ~p_0
  3: p_0 | ~p_1
3:
  3: 'True'
