p_0:
  constraint: A + B = C + D
  predicate: p
  streams:
    W:
      direction: input
      name: w
    X:
      direction: input
      name: x
    Y:
      direction: input
      name: y
    Z:
      direction: input
      name: z
  substitutions:
    A: W
    B: X
    C: Y
    D: Z
